"""initial_schema

Revision ID: 540c4bab1513
Revises: 
Create Date: 2026-05-25 12:22:16.687017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540c4bab1513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_name', sa.String(length=200), nullable=True),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('n_clusters', sa.Integer(), nullable=True),
    sa.Column('silhouette_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('davies_bouldin_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('inertia', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('runtime_seconds', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('avg_clv', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('churn_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('revenue_share', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('marketing_strategy', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('membership_status', sa.String(length=20), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('clv_estimate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_frequency', sa.Integer(), nullable=True),
    sa.Column('days_since_last_purchase', sa.Integer(), nullable=True),
    sa.Column('cart_abandonment_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('return_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('email_open_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('app_usage_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=True),
    sa.Column('rfm_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('engagement_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('churn_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('value_tier', sa.String(length=20), nullable=True),
    sa.Column('predicted_clv_90d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preferred_category', sa.String(length=100), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_customers_region'), 'customers', ['region'], unique=False)
    op.create_index(op.f('ix_customers_segment_id'), 'customers', ['segment_id'], unique=False)
    op.create_index(op.f('ix_customers_value_tier'), 'customers', ['value_tier'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('discount_applied', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_customers_value_tier'), table_name='customers')
    op.drop_index(op.f('ix_customers_segment_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_region'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_table('segments')
    op.drop_table('ml_runs')
    # ### end Alembic commands ###
